mdapi/src/objects/Category__c.object
<CustomObject>
    <label>Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Reimbursable_Percentage__c</fullName>
        <description>This field describes what percentage of this expense category can be reimbursed.</description>
        <label>Reimbursable Percentage</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

force-app/main/default/objects/Exchange_Rate__c/Exchange_Rate__c.object-meta.xml
<CustomObject>
    <label>Exchange Rate</label>
    <nameField>
        <label>Exchange Rate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exchange Rates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi/src/objects/Expense_Item__c.object
<CustomObject>
    <label>Expense Item</label>
    <nameField>
        <label>Expense Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Expense Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Category__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Category</label>
        <referenceTo>Category__c</referenceTo>
        <relationshipLabel>Expense Items</relationshipLabel>
        <relationshipName>Expense_Items</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

force-app/main/default/objects/Expense_Item__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <description>The total price of the business expense.</description>
    <label>Amount</label>
    <precision>8</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Expense_Item__c/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <defaultValue>&quot;USD&quot;</defaultValue>
    <label>Currency</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Currency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Expense_Item__c/fields/Exchange_Rate__c.field-meta.xml
<CustomField>
    <fullName>Exchange_Rate__c</fullName>
    <label>Exchange Rate</label>
    <precision>18</precision>
    <required>true</required>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Expense_Item__c/fields/Reimbursable_Amount__c.field-meta.xml
<CustomField>
    <fullName>Reimbursable_Amount__c</fullName>
    <label>Reimbursable Amount</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/globalValueSets/Currency.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>HUN</fullName>
        <default>true</default>
        <label>HUN</label>
    </customValue>
    <customValue>
        <fullName>INR</fullName>
    </customValue>
    <customValue>
        <fullName>ISK</fullName>
    </customValue>
    <customValue>
        <fullName>JPY</fullName>
    </customValue>
    <customValue>
        <fullName>USD</fullName>
    </customValue>
    <masterLabel>Currency</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ExpenseItemTriggerHandler.cls
public class ExpenseItemTriggerHandler extends TriggerHandler {

    public override void beforeInsert() {
        calculateReimbursableAmount(Trigger.new);
    }

    public override void afterInsert(){}

    public override void beforeUpdate(){
        calculateReimbursableAmount(Trigger.new);
    }

    public override void afterUpdate(){}

    public override void beforeDelete(){}

    public override void afterDelete(){}

    public void calculateReimbursableAmount(List<Expense_Item__c> ExpenseItemList) {

        for (Expense_Item__c expenseItem : ExpenseItemList) {
            if(expenseItem.Currency__c == 'USD') {
                expenseItem.Exchange_Rate__c = 1;
            } else {
                expenseItem.Exchange_Rate__c = 0;
            }
        }

        Set<Id> catergoryIds = new Set<Id>();

        for (Expense_Item__c ei : ExpenseItemList) {
          catergoryIds.add(ei.Category__c);
	    }

        Map<Id, Category__c> categories = new Map<Id, Category__c>([
            SELECT Id, Reimbursable_Percentage__c
            FROM Category__c
            WHERE Id IN:catergoryIds
        ]);

        for (Expense_Item__c expenseI : ExpenseItemList) {
           Id categoryId = expenseI.Category__c;
          expenseI.Reimbursable_Amount__c = expenseI.Exchange_Rate__c * expenseI.Amount__c * categories.get(categoryId).Reimbursable_Percentage__c / 100;
        }
    }
}