force-app/main/default/objects/Exchange_Rate__c/Exchange_Rate__c.object-meta.xml
<CustomObject>
    <label>Exchange Rate</label>
    <nameField>
        <label>Exchange Rate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exchange Rates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Exchange_Rate__c/fields/Rate__c.field-meta.xml
<CustomField>
    <fullName>Rate__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Rate</label>
    <precision>14</precision>
    <required>true</required>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Exchange_Rate__c/fields/Rate_Date__c.field-meta.xml
<CustomField>
    <fullName>Rate_Date__c</fullName>
    <defaultValue>Today()</defaultValue>
    <label>Rate Date</label>
    <type>Date</type>
</CustomField>

mdapi/src/objects/Expense_Item__c.object
<CustomObject>
    <label>Expense Item</label>
    <nameField>
        <label>Expense Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Expense Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Expense_Item__c/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <defaultValue>&quot;USD&quot;</defaultValue>
    <label>Currency</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Currency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Expense_Item__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <description>The date on the expense receipt.</description>
    <label>Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Expense_Item__c/fields/Exchange_Rate__c.field-meta.xml
<CustomField>
    <fullName>Exchange_Rate__c</fullName>
    <label>Exchange Rate</label>
    <precision>18</precision>
    <required>true</required>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/globalValueSets/Currency.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>HUN</fullName>
        <default>true</default>
        <label>HUN</label>
    </customValue>
    <customValue>
        <fullName>INR</fullName>
    </customValue>
    <customValue>
        <fullName>ISK</fullName>
    </customValue>
    <customValue>
        <fullName>JPY</fullName>
    </customValue>
    <customValue>
        <fullName>USD</fullName>
    </customValue>
    <masterLabel>Currency</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ExchangeRateBatch.cls
public class ExchangeRateBatch implements Database.Batchable<sObject>, Database.AllowsCallouts {
    
// "Create a method in ExchangeRateBatch to populateExchangeRates. The method will:
// 1. Accespts a list of Expense_Item__c
// 2. Loop through the list of Expense_Item__c and organize them into a map where the key is the Date and the value is a Set of currencies for that date.
// 3. Call ExchangeRateService.getFXRates for every Map entry.
// 4. Append the results of getFXRates to a map where the key is formatted date string concatendated with currency code and delimited with colon sign. 
// Example: ""2019-05-09:JPY""
// The value of the map is Exchange_Rate__c object
// 5. Return the map"

    private String query;
    
    public ExchangeRateBatch (String soql){
        query = soql;
    }
    
    // The batch job starts

    public Database.Querylocator start(Database.BatchableContext bc){
        //String query = 'SELECT Id, Name FROM Account';
        return Database.getQuerylocator(query);
    } 

    public Map<String, Exchange_Rate__c> populateExchangeRates(List<Expense_Item__c> expenseItems){
        Map<Date, Set<String>> expenseItemsMap = new Map<Date, Set<String>>();
        Set<String> currenciesSetForDate = new Set<String>();

        // output a map with all expense item dates as key and a set of currencies as values
        for (Expense_Item__c expenseItem: expenseItems) {

            if(expenseItemsMap.get(expenseItem.Date__c)!= null){     
                currenciesSetForDate = expenseItemsMap.get(expenseItem.Date__c);
            }
                currenciesSetForDate.add(expenseItem.Currency__c);
                expenseItemsMap.put(expenseItem.Date__c, currenciesSetForDate);
        }


        //output a map with joined date_and_currency as key and exchange rate as value
        Map<String, Exchange_Rate__c> exchangeRateByDateAndCurrency = new Map<String, Exchange_Rate__c>();

        List<Exchange_Rate__c>FXRatesList;

        // callout for missing date and currency
        for (Date rateDate : expenseItemsMap.keySet()){
            List<String> currenciesToGet = new List<String>(expenseItemsMap.get(rateDate));
            ExchangeRateService exchangeRateService = new ExchangeRateService(rateDate, currenciesToGet);
            FXRatesList = exchangeRateService.getFXRates();

        for (Exchange_Rate__c exchangeRateObject: FXRatesList){
            if (rateDate == exchangeRateObject.Rate_Date__c && currenciesToGet.contains(exchangeRateObject.Currency__c) ){
                String exchangeRateKey = rateDate + ':' + exchangeRateObject.Currency__c;
                exchangeRateByDateAndCurrency.put(exchangeRateKey, exchangeRateObject);
            }
        }
      }

        for (Expense_Item__c expenseItem: expenseItems) {
            String exchangeRateKey = expenseItem.Date__c + ':' + expenseItem.Currency__c; 
            Boolean exchangeRateExists = exchangeRateByDateAndCurrency.get(exchangeRateKey) != null;
            if(exchangeRateExists){
                expenseItem.Exchange_Rate__c = 1 / exchangeRateByDateAndCurrency.get(exchangeRateKey).Rate__c;
            }
        }
    
        update expenseItems;

        if(FXRatesList.size() > 0){
            upsert FXRatesList;
        }
        return exchangeRateByDateAndCurrency;
    }
        // The batch job executes and operates on one batch of records
    public void execute(Database.BatchableContext bc, List<sObject> expenseItems) {
            populateExchangeRates(expenseItems);
        }
    
        // The batch job finishes
    public void finish(Database.BatchableContext bc){
            AsyncApexJob job = [SELECT Id, Status FROM AsyncApexJob WHERE Id = :bc.getJobId()]; 
            System.debug('>>>> finish ' + job.Status);
        }
    }